# Generated by Django 3.2.8 on 2021-10-29 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='slug',
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AlterField(
            model_name='author',
            name='firstname',
            field=models.CharField(max_length=32, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='author',
            name='lastname',
            field=models.CharField(max_length=32, verbose_name='Last name'),
        ),
    ]
