# Generated by Django 3.2.8 on 2021-11-01 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0003_auto_20211029_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='firstname',
            field=models.CharField(max_length=32, verbose_name="Ім'я"),
        ),
    ]
