# Generated by Django 3.2.8 on 2021-10-29 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('author', '0002_auto_20211029_1241'),
        ('edition', '0002_alter_edition_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='book_images')),
                ('title', models.CharField(max_length=128)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('number', models.PositiveSmallIntegerField(default=1)),
                ('ISBN', models.PositiveBigIntegerField()),
                ('numberOfPages', models.PositiveIntegerField()),
                ('publicationYear', models.PositiveSmallIntegerField()),
                ('coverType', models.CharField(choices=[('Softcover', "М'яка"), ('Hardcover', 'Тверда'), ('Supercover', 'Супер')], default='Hardcover', max_length=30)),
                ('paperType', models.CharField(choices=[('Newspaper', 'Газетний'), ('Offset', 'Офсетний')], default='Offset', max_length=30)),
                ('description', models.TextField()),
                ('isAvailable', models.BooleanField(default=True)),
                ('isHot', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='author.author')),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edition.edition')),
            ],
        ),
    ]
