# Generated by Django 3.2.8 on 2021-10-29 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0003_auto_20211029_1903'),
        ('edition', '0003_alter_edition_title'),
        ('book', '0002_book_isnew'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Назва')),
                ('slug', models.CharField(blank=True, max_length=128)),
            ],
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='author.author', verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='book',
            name='coverType',
            field=models.CharField(choices=[('Softcover', "М'яка"), ('Hardcover', 'Тверда'), ('Supercover', 'Супер')], default='Hardcover', max_length=30, verbose_name='Тип обкладинки'),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='book',
            name='edition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edition.edition', verbose_name='Видавництво'),
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(upload_to='book_images', verbose_name='Зображення'),
        ),
        migrations.AlterField(
            model_name='book',
            name='isAvailable',
            field=models.BooleanField(default=True, verbose_name='Доступна'),
        ),
        migrations.AlterField(
            model_name='book',
            name='isHot',
            field=models.BooleanField(default=False, verbose_name='Популярна'),
        ),
        migrations.AlterField(
            model_name='book',
            name='isNew',
            field=models.BooleanField(default=False, verbose_name='Новинка'),
        ),
        migrations.AlterField(
            model_name='book',
            name='number',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Кількість книг'),
        ),
        migrations.AlterField(
            model_name='book',
            name='numberOfPages',
            field=models.PositiveIntegerField(verbose_name='Кількість сторінок'),
        ),
        migrations.AlterField(
            model_name='book',
            name='paperType',
            field=models.CharField(choices=[('Newspaper', 'Газетний'), ('Offset', 'Офсетний')], default='Offset', max_length=30, verbose_name='Тип паперу'),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Ціна'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publicationYear',
            field=models.PositiveSmallIntegerField(verbose_name='Рік публікації'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=128, verbose_name='Назва'),
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='book.category', verbose_name='Категорія'),
        ),
    ]
