# Generated by Django 3.2.8 on 2022-01-08 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_alter_category_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numberOfOrders', models.PositiveBigIntegerField(verbose_name='Кількість замовлень')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.book')),
            ],
            options={
                'ordering': ['-numberOfOrders'],
            },
        ),
    ]
