# Generated by Django 3.2.8 on 2021-11-17 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='id',
        ),
        migrations.AddField(
            model_name='order',
            name='orderNumber',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
