# Generated by Django 3.2.8 on 2021-11-17 20:23

import cart.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_alter_order_ordernumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='userPhone',
            field=models.CharField(max_length=13, validators=[cart.models.phoneNationalFormatValidator]),
        ),
    ]
