# Generated by Django 3.2.8 on 2021-11-17 20:31

import cart.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_alter_order_userphone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='userPhone',
            field=models.CharField(max_length=13, validators=[cart.models.phoneNationalFormatValidator, cart.models.phoneLessNumbersValidator]),
        ),
    ]
