# Generated by Django 3.2.8 on 2021-11-18 09:13

import cart.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_alter_order_userphone'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery',
            field=models.CharField(choices=[('NovaPoshta', 'Нова Пошта'), ('UkrPoshta', 'Укрпошта')], default='NovaPoshta', max_length=10, verbose_name='Доставка'),
        ),
        migrations.AlterField(
            model_name='order',
            name='orderNumber',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Номер замовлення'),
        ),
        migrations.AlterField(
            model_name='order',
            name='userEmail',
            field=models.EmailField(max_length=254, verbose_name='Електронна адреса'),
        ),
        migrations.AlterField(
            model_name='order',
            name='userFirstName',
            field=models.CharField(max_length=32, verbose_name="Ім'я"),
        ),
        migrations.AlterField(
            model_name='order',
            name='userLastName',
            field=models.CharField(max_length=32, verbose_name='Прізвище'),
        ),
        migrations.AlterField(
            model_name='order',
            name='userPatronymic',
            field=models.CharField(max_length=32, verbose_name='По-батькові'),
        ),
        migrations.AlterField(
            model_name='order',
            name='userPhone',
            field=models.CharField(max_length=13, validators=[cart.models.phoneNationalFormatValidator, cart.models.phoneLessNumbersValidator, cart.models.phoneValidFormatValidator], verbose_name='Номер телефону'),
        ),
    ]
