# Generated by Django 3.2.8 on 2021-11-18 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_auto_20211118_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='deliveryAddress',
            field=models.CharField(default='', max_length=128),
        ),
    ]
