# Generated by Django 3.2.8 on 2021-11-18 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_orderedbook'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderedbook',
            old_name='orderNumber',
            new_name='order',
        ),
    ]
