# Generated by Django 3.2.8 on 2021-11-18 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0010_rename_ordernumber_orderedbook_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderedbook',
            old_name='order',
            new_name='orderNumber',
        ),
    ]
