# Generated by Django 3.2.8 on 2021-11-20 13:11

import cart.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_alter_category_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cart', '0011_rename_order_orderedbook_ordernumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='number',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Кількість'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.book', verbose_name='Книга'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Користувач'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery',
            field=models.CharField(choices=[('NovaPoshta', 'Нова Пошта'), ('UkrPoshta', 'Укрпошта'), ('Justin', 'Justin')], default='NovaPoshta', max_length=10, verbose_name='Доставка'),
        ),
        migrations.AlterField(
            model_name='order',
            name='deliveryAddress',
            field=models.CharField(default='', max_length=128, verbose_name='Адреса відділення'),
        ),
        migrations.AlterField(
            model_name='orderedbook',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.book', verbose_name='Книга'),
        ),
        migrations.AlterField(
            model_name='orderedbook',
            name='orderNumber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.order', verbose_name='Номер замовлення'),
        ),
        migrations.AlterField(
            model_name='orderedbook',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Користувач'),
        ),
    ]
