# Generated by Django 3.2.8 on 2021-11-20 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0012_auto_20211120_1511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='number',
        ),
    ]
